### PR TITLE
Player Avatars

### PR DESCRIPTION
**Pull request by jaydeluca**
Could use some help on this one. I have the upload handled (on a basic level so far), but I think we need to determine:

* Naming convention for images - my initial thought was to just save them under the player's name or something similar, or we could just use some kind of date string or hash of some kind
* Where to store them - this is the hard part imo. At first I was uploading them to the server directory/uploads, but I can't figure out how to access them on the frontend. So then I changed the upload path to be in the client directory. I haven't used a webpack build with this configuration in the past, so im having a hard time figuring out how to reference these uploaded files.
* Upload validation - only accept certain file types/sizes (this part shouldn't be difficult)

I tried throwing them in the src/assets folder, but I _believe_ webpack needs to bundle everything in the src folder and compiles it all, so that wouldnt work.

### CODE REVIEW

**Comment by adigitalmonk** [comment]
I haven’t had a chance to look at the code but if you limit the file size you could base64 encode it and then shove that into the database. I haven’t looked into how to handle that client side... not even sure the complexity on either side. But I just woke up and it was the first thing that came to mind.

**Comment by ianarsenault** [comment]
I have a few questions as I've never handled file uploads with node. Are we trying to move the uploaded file to a directory on either client/server with a unique name (hash or base64 encoded), and storing that unique image name in the DB?

**Comment by ianarsenault** [comment]
I saw that you started the image upload functionality on the edit player page, wasn't sure if that was intentional, so I added a few things to the new player page.

-  preview load of user selected image
-  front-side file size check for the image.

**Comment by jaydeluca** [comment]
So we are going to store the image as a bas64 hash directly in the db, or that's the plan at least right now. I'm struggling to get my schema changes to take effect locally, but I think we've got it pretty close

**Comment by ianarsenault** [comment]
@jaydeluca I got upload for images working with the ability to display image when you click on the **edit** button of a particular player. However when you you try to update an existing players info the app crashes.

It seems to be throwing multiple **undefined** giving a URL path of `http://localhost:8081/players/undefined` with undefined needing to be the player ID.

Image
Image

This also seems to be happening whether or not I add an image to a new player then try to update

Not sure what the problem is that is causing this, but will continue to work on it.

**Comment by ianarsenault** [comment]
I was able to resolve the issue with the app crashing on Update. Now we should be able to add and update along with the images fine. However I'm still unsure as the proper way to store images. Currently we're only able to send images less the 80kb, or else it throws `Error: request entity too large` for the file. I think this may have something to do with how I set it up to store as String. 

Now that the app doesn't crash on update I'll give another shot at using `type: Buffer` for the avatar.

**Pull request merged**
