### PR TITLE
Leaderboard endpoints, services, and saving of each game

### PR DESCRIPTION
**Pull request by jkys**
Many updates for leaderboards as well as getting the player profile page intialized

- Edit LeaderBoard component to contain looped table
- Added initial PlayerProfile component
- Updated battles to post each game to leaderboard table
- Created leaderboard service to post new games, get all games, and get games for specific member (wip last one)
- Added db methods for game logs models
- Created routes for leaderboards

### CODE REVIEW

**Comment by jaydeluca** [comment]
Player 4 has entered the building.

Nice work dude

**Comment by jkys** [comment]
I changed GameLogs to LeaderBoards, @jaydeluca do you have any disagreements? I am open to both but figured leaderboards was more of a standard name

**Comment by jaydeluca** [comment]
All good on my end

**Comment by jkys** [comment]
I was thinking that I should change LeaderBoard back to GameLogs and leave LeaderBoard for an actual LeaderBoard of who has won the most games, while GameLogs is more of a record keeping table/service

**Comment by j-arsenault** [comment]
I think that is a good idea @jkys

**Comment by jkys** [comment]
@jaydeluca & @ianarsenault: updated to be gamelogs instead of leaderboards for later usage.

@jaydeluca 👍 for foresight at first

**Pull request merged**
